### ISSUE TITLE
 returned non-zero exit status 1.

### ISSUE THREAD

**Issue by wes1993** [GitBib/pymkv#5]
**Describe the bug**
Hello, when mkvmerge merge the video files i have this error:
returned non-zero exit status 1.

**To Reproduce**
Try to merge 2 mkv files

**Expected behavior**
Correct return code

**Screenshots**

**Software (please complete the following information):**
 - OS: Windows 11
 - MKVToolNix version 80

**Additional context**
Seems also that the title passed (Pippo) won't works....
LOG:
```
Traceback (most recent call last):
  File "C:\Users\Stefano\Desktop\PlexTelegram\plextelegram_v2.py", line 325, in <module>
    mergemovie()
  File "C:\Users\Stefano\Desktop\PlexTelegram\plextelegram_v2.py", line 303, in mergemovie
    mkv1.mux("media/Shark 2 - L'abisso (2023)/SHARK 2-L'ABISSO (2023).mkv", "Pippo")
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python310\lib\site-packages\pymkv\MKVFile.py", line 263, in mux
    sp.run(self.command(output_path, subprocess=True), stdout=open(devnull, 'wb'), check=True)
  File "C:\Users\Stefano\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['mkvmerge', '-o', "media/Shark 2 - L'abisso (2023)/SHARK 2-L'ABISSO (2023).mkv", '--title', "PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms", '--track-name', '0:@Serietvfilms', '--language', '0:und', '--default-track', '0:1', '--forced-track', '0:0', '-d', '0', '-A', '-S', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '1:Surround', '--language', '1:ita', '--default-track', '1:1', '--forced-track', '1:0', '-D', '-a', '1', '-S', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '2:Surround', '--language', '2:eng', '--default-track', '2:0', '--forced-track', '2:0', '-D', '-a', '2', '-S', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '3:Forced', '--language', '3:ita', '--default-track', '3:1', '--forced-track', '3:1', '-D', '-A', '-s', '3', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '4:Regular Tradotti', '--language', '4:ita', '--default-track', '4:0', '--forced-track', '4:0', '-D', '-A', '-s', '4', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '5:Forced', '--language', '5:eng', '--default-track', '5:0', '--forced-track', '5:0', '-D', '-A', '-s', '5', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '6:Regular', '--language', '6:eng', '--default-track', '6:0', '--forced-track', '6:0', '-D', '-A', '-s', '6', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--language', '7:fre', '--default-track', '7:0', '--forced-track', '7:0', '-D', '-A', '-s', '7', "media/Shark 2 - L'abisso (2023)/PT1-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '0:@Serietvfilms', '--language', '0:und', '--default-track', '0:1', '--forced-track', '0:0', '-d', '0', '-A', '-S', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '1:Surround', '--language', '1:ita', '--default-track', '1:1', '--forced-track', '1:0', '-D', '-a', '1', '-S', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '2:Surround', '--language', '2:eng', '--default-track', '2:0', '--forced-track', '2:0', '-D', '-a', '2', '-S', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '3:Forced', '--language', '3:ita', '--default-track', '3:1', '--forced-track', '3:1', '-D', '-A', '-s', '3', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '4:Regular Tradotti', '--language', '4:ita', '--default-track', '4:0', '--forced-track', '4:0', '-D', '-A', '-s', '4', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '5:Forced', '--language', '5:eng', '--default-track', '5:0', '--forced-track', '5:0', '-D', '-A', '-s', '5', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--track-name', '6:Regular', '--language', '6:eng', '--default-track', '6:0', '--forced-track', '6:0', '-D', '-A', '-s', '6', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv", '--language', '7:fre', '--default-track', '7:0', '--forced-track', '7:0', '-D', '-A', '-s', '7', "media/Shark 2 - L'abisso (2023)/PT2-SHARK 2-L'ABISSO (2023) @Serietvfilms.mkv"]' returned non-zero exit status 1.
```

**Comment by GitBib** [comment]
Sometimes this problem happens. I hope to improve the mux process.

**Comment by GitBib** [comment]
MkvToolNix when it displays a warning, they give a status not equal to 0. That's why I added a little more information. And the behavior is a bit better now. #7
